displayName: Maintenance Mode Plugin

type: middleware

import: github.com/CitronusAcademy/traefik-maintenance-plugin

summary: "A middleware that checks if a service is in maintenance mode and returns an appropriate status code"

testData:
  endpoint: "https://api.citronus.pro/admin/api/system-config/?format=json"
  cacheDurationInSeconds: 10
  requestTimeoutInSeconds: 5
  maintenanceStatusCode: 512
  skipPrefixes:
    - "/admin"
    - "/pgadmin"

id: maintenanceCheck
