displayName: Maintenance Mode Plugin

type: middleware

import: github.com/CitronusAcademy/traefik-maintenance-plugin

summary: "A middleware that checks if a service is in maintenance mode and returns an appropriate status code"

testData:
  endpoint: "http://maintenance-service/v1/configurations/"
  cacheDurationInSeconds: 10
  requestTimeoutInSeconds: 5
  maintenanceStatusCode: 512
  skipPrefixes:
    - "/admin"
  skipHosts:
    - admin.example.com
    - monitoring.example.com
    - "*.internal.example.com"
  secretHeader: "X-Plugin-Secret"
  secretHeaderValue: "example-secret-token"

id: maintenanceCheck
